import { useEffect } from 'react'
import Head from 'next/head'
import { client } from '../lib/sanityClient'
import toast, { Toaster } from 'react-hot-toast'

import Header from '../components/Header'
import Hero from '../components/Hero'
import { useAddress, useMetamask } from '@thirdweb-dev/react'

const style = {
  container: `before:content-['']  flex flex-col justify-center items-center before:bg-red-500 before:absolute before:top-0 before:left-0 before:right-0 before:bottom-0 before:bg-[url('/hero.png')] before:bg-cover before:bg-center before:opacity-40 before:blur-[1px]`,
  walletConnectWrapper: `relative flex flex-col justify-center items-center h-screen w-screen bg-[#3b3d42] `,
  details: `text-lg z-50 text-center text-[#cccccc] font-semibold mt-4`,
}

export default function Home() {
  const connectMetaMask = useMetamask()
  const address = useAddress()

  const welcomeUser = (userName, toastHandler = toast) => {
    toastHandler.success(
      `Welcome back ${userName != 'Unnamed' ? `${userName}` : ''}!`,
      {
        style: {
          background: '#04111d',
          color: '#fff',
        },
      }
    )
  }

  // Ver se o metamask retorna algum tipo de dado como o nome de usuário

  useEffect(() => {
    if (!address) return
    ;(async () => {
      const userDoc = {
        _type: 'users',
        _id: address,
        userName: 'Unnamed',
        walletAddress: address,
      }

      const result = await client.createIfNotExists(userDoc)
      // console.log(result)
      welcomeUser(result.userName)
    })()
    /** ⬆⬆ Create an anonymous function and call it immediately ⬆⬆
     *  IIFE (Immediately Invoked Functional Expressions)
     */
  }, [address])

  return (
    <>
      {/* Se o usuario não estiver conectado mandar para home */}
      <Head>
        <title>OpenSea, the largest NFT marketplace</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        <Toaster position="top-center" reverseOrder={false} />
        {!address ? (
          <div className={style.walletConnectWrapper}>
            <div className={style.container}>
              <button
                onClick={connectMetaMask}
                href="#_"
                className="relative inline-flex items-center justify-center px-10 py-4 overflow-hidden font-mono font-medium tracking-tighter text-white bg-gray-800 rounded-lg group"
              >
                <span className="absolute w-0 h-0 transition-all duration-500 ease-out bg-[#2081e2] rounded-full group-hover:w-56 group-hover:h-56"></span>
                <span className="absolute inset-0 w-full h-full -mt-1 rounded-lg opacity-30 bg-gradient-to-b from-transparent via-transparent to-gray-700"></span>
                <span className="relative">Connect Wallet</span>
              </button>
              <div className={style.details}>
                You need Metamask to be <br /> able to run this app.
              </div>
            </div>
          </div>
        ) : (
          <>
            <Header />
            <Hero />
          </>
        )}
      </div>
    </>
  )
}
