import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <div>
      <Head>
        <title>OpenSea, the largest NFT marketplace</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Hero />
    </div>
  )
}
